<a href="https://colab.research.google.com/github/Krahjotdaan/MachineLearning/blob/main/NumPy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Практика по  numpy

Данный ноутбук представляет из себя  практическое задание.



В данном блоке вы должны выполнить несколько простых упражнений на работу с векторами в numpy.
Пишите свой код в ячейках после каждого задания. Для начала импортируйте библиотеку

In [ ]:
import numpy as np

Ниже считывается файл с минимальными температурами по дням в период с 01.01.2003 по 25.09.2005 в г. Москва

In [ ]:
with open('weather_min.txt') as f:
  l = f.readlines()
l = np.array([temp[:-1] for temp in l[:-1]])
l = l[l != ''].astype(float)
l

array([-28., -12.,  -9., -12., -19., -28., -30., -29., -21., -24., -28.,
       -26., -11., -15.,  -8.,  -5.,  -3.,  -2.,  -1.,  -2.,  -6.,  -6.,
        -6.,  -8.,  -8.,  -2.,  -2.,  -2.,  -3.,  -2.,  -9., -18., -21.,
       -23., -22., -15., -15., -12.,  -8., -12., -18., -22., -22., -10.,
        -9., -22., -23., -10.,  -8.,  -3., -14., -12.,  -9., -12., -13.,
        -6.,  -6.,  -9., -12., -14., -17., -18., -18., -15., -16., -16.,
       -13., -13.,  -7.,  -5.,  -2.,  -3.,  -5.,  -5.,  -6.,  -8.,  -7.,
        -9.,  -8., -11., -14., -15.,  -5.,  -3., -10., -11.,  -6.,  -3.,
        -2.,   1.,  -5.,  -6.,  -8.,   0.,  -1.,  -1.,   0.,   0.,   0.,
        -3.,  -5.,   0.,   3.,   1.,   0.,   4.,   2.,   2.,   0.,   3.,
         5.,   3.,   3.,   0.,  -6.,  -7.,  -6.,  -3.,   1.,   6.,   5.,
         7.,   5.,   4.,   3.,   2.,   8.,   5.,   3.,  11.,  10.,   9.,
        14.,  16.,  12.,  10.,   3.,   2.,   6.,  10.,  15.,  15.,  12.,
        12.,  12.,  12.,  13.,  12.,   4.,   3.,   

# 1. Январь
Выведите все значения температуры за январь 2003 года

In [ ]:
l[:31]

array([-28., -12.,  -9., -12., -19., -28., -30., -29., -21., -24., -28.,
       -26., -11., -15.,  -8.,  -5.,  -3.,  -2.,  -1.,  -2.,  -6.,  -6.,
        -6.,  -8.,  -8.,  -2.,  -2.,  -2.,  -3.,  -2.,  -9.])

# 2. Последний день
Измените температуру последнего дня на любое число

In [ ]:
l[30] + 10

1.0

# 3. Не люблю холода
Замените все отрицательные температуры на положительные(не изменяя значения температур). Подсказка: np.abs()

In [ ]:
np.abs(l)

#4. Удачная число
Найдите индексы всех чисел равных 7

In [ ]:
np.where(l == 7)

(array([121, 155, 167, 169, 244, 247, 250, 251, 256, 257, 270, 276, 279,
        281, 508, 511, 588, 590, 591, 610, 625, 832, 834, 856, 859, 860,
        864, 961, 970, 975, 984, 986, 994, 996]),)

# 5. Неудуачное число
Замените все числа, кратные 13 или 4 на число 7.

In [ ]:
l[(l % 13 == 0) | (l % 4 == 0)] = 7
l

array([  7.,   7.,  -9.,   7., -19.,   7., -30., -29., -21.,   7.,   7.,
         7., -11., -15.,   7.,  -5.,  -3.,  -2.,  -1.,  -2.,  -6.,  -6.,
        -6.,   7.,   7.,  -2.,  -2.,  -2.,  -3.,  -2.,  -9., -18., -21.,
       -23., -22., -15., -15.,   7.,   7.,   7., -18., -22., -22., -10.,
        -9., -22., -23., -10.,   7.,  -3., -14.,   7.,  -9.,   7.,   7.,
        -6.,  -6.,  -9.,   7., -14., -17., -18., -18., -15.,   7.,   7.,
         7.,   7.,  -7.,  -5.,  -2.,  -3.,  -5.,  -5.,  -6.,   7.,  -7.,
        -9.,   7., -11., -14., -15.,  -5.,  -3., -10., -11.,  -6.,  -3.,
        -2.,   1.,  -5.,  -6.,   7.,   7.,  -1.,  -1.,   7.,   7.,   7.,
        -3.,  -5.,   7.,   3.,   1.,   7.,   7.,   2.,   2.,   7.,   3.,
         5.,   3.,   3.,   7.,  -6.,  -7.,  -6.,  -3.,   1.,   6.,   5.,
         7.,   5.,   7.,   3.,   2.,   7.,   5.,   3.,  11.,  10.,   9.,
        14.,   7.,   7.,  10.,   3.,   2.,   6.,  10.,  15.,  15.,   7.,
         7.,   7.,   7.,   7.,   7.,   7.,   3.,   

#6. Статистика
Найдите минимум, максимум, среднее значение и медиану

In [ ]:
l.min()


-30.0

In [ ]:
l.max()

19.0

In [ ]:
l.mean()

1.4593781344032097

In [ ]:
np.median(l)

3.0

# 7. Неповторимый
Сколько уникальных значений температур содержит файл? Подсказка: np.unique()

In [ ]:
np.unique(l)

array([-30., -29., -28., -26., -24., -23., -22., -21., -20., -19., -18.,
       -17., -16., -15., -14., -13., -12., -11., -10.,  -9.,  -8.,  -7.,
        -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,   1.,   2.,   3.,   4.,
         5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,
        16.,  17.,  18.,  19.])

# 8. Глобальное потепление
Увеличьте значение температуры каждого дня на случайное число от 0 до 1 (случайные числа должны быть разными)

In [ ]:
l = list(map(lambda l: l + np.random.default_rng().random(), l))
l

# Дополнительно

#### Задание 1.

Создайте вектор из 100 чисел x = [1,...,...,...,137]

len(x) == 100

In [ ]:
np.linspace(1, 137, 100)

array([  1.        ,   2.37373737,   3.74747475,   5.12121212,
         6.49494949,   7.86868687,   9.24242424,  10.61616162,
        11.98989899,  13.36363636,  14.73737374,  16.11111111,
        17.48484848,  18.85858586,  20.23232323,  21.60606061,
        22.97979798,  24.35353535,  25.72727273,  27.1010101 ,
        28.47474747,  29.84848485,  31.22222222,  32.5959596 ,
        33.96969697,  35.34343434,  36.71717172,  38.09090909,
        39.46464646,  40.83838384,  42.21212121,  43.58585859,
        44.95959596,  46.33333333,  47.70707071,  49.08080808,
        50.45454545,  51.82828283,  53.2020202 ,  54.57575758,
        55.94949495,  57.32323232,  58.6969697 ,  60.07070707,
        61.44444444,  62.81818182,  64.19191919,  65.56565657,
        66.93939394,  68.31313131,  69.68686869,  71.06060606,
        72.43434343,  73.80808081,  75.18181818,  76.55555556,
        77.92929293,  79.3030303 ,  80.67676768,  82.05050505,
        83.42424242,  84.7979798 ,  86.17171717,  87.54

#### Задание 2.
Даны векторы


*   a = [1,3,7],
*   b = [2,-1,5]


Найдите скалярное произведение векторов **2a** и **-b**

In [ ]:
a = np.array([1, 3, 7])
b = np.array([2, -1, 5])
np.dot(np.dot(a, 2), -b)

-68

#### Задание 3.

Вам дан вектор a = [1,2,5,10]

Превратите данный вектор в [0,4,0,20]

в одну строчку. Да, нужно угадать формулу.

In [ ]:
a = np.array([1, 2, 5, 10])
a = np.array(list(a[i] * 0 if i % 2 == 0 else a[i] * 2 for i in range(len(a))))
a

array([ 0,  4,  0, 20])