<a href="https://colab.research.google.com/github/Krahjotdaan/MachineLearning/blob/main/NumPy_practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Всё и вся про numpy

В этом ноутбуке в каждой ячейке отдельное задание - читайте комментарий в ячейке.

**ВАЖНО** - выполнить задания надо с использованием библиотеки!

подсказки:
- тензор - это многомерная матрица
- измерить время операции можно, поставив в начале строки %timeit
        например: %timeit x+x

In [ ]:
# импорт библиотеки
import numpy as np

In [ ]:
# перевернуть вектор задом наперед
a = np.array([1, 2, 3, 4])
a[::-1]

array([4, 3, 2, 1])

In [ ]:
# создать матрицу 3х3 из значений от 0 до 8
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# создать матрицу 3х3 из нулей и диагональю из 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# создать тензор 3х3х3 из случайных чисел
np.random.random((3, 3, 3))

array([[[0.44724968, 0.88029969, 0.27306691],
        [0.7939959 , 0.7453421 , 0.36087175],
        [0.89695919, 0.50931538, 0.45129369]],

       [[0.21699288, 0.74998199, 0.6808775 ],
        [0.73957894, 0.93058212, 0.44794474],
        [0.54109533, 0.33007923, 0.91364475]],

       [[0.85168582, 0.04468645, 0.41924544],
        [0.70935026, 0.19653004, 0.98283213],
        [0.86792398, 0.53633586, 0.028935  ]]])

In [ ]:
# создать матрицу 10х10 из случайных чисел и вывести минимальное и максимальное значения
a = np.random.random((10, 10))
print(a)
print(a.max())
print(a.min())

[[0.64526786 0.50708268 0.20581455 0.73520823 0.96411973 0.61637654
  0.91029275 0.68856257 0.69539853 0.93454024]
 [0.98811575 0.72856657 0.2998111  0.28459793 0.68421128 0.3653897
  0.00113768 0.88078532 0.25894666 0.76810772]
 [0.61801207 0.72230809 0.01820827 0.9155601  0.97307082 0.77598075
  0.01071405 0.56405452 0.60767366 0.05026862]
 [0.05584821 0.65261298 0.69885557 0.18001218 0.85675402 0.56105411
  0.86996676 0.74324515 0.94478489 0.58592682]
 [0.22657528 0.38182246 0.22746982 0.65472301 0.33427616 0.76674765
  0.4607254  0.13872329 0.71707778 0.89240907]
 [0.51810378 0.95879792 0.69872091 0.67137923 0.95810056 0.08108715
  0.53316791 0.02899446 0.76048058 0.53334513]
 [0.66174577 0.95177924 0.18381414 0.08042076 0.16529196 0.96994924
  0.1342524  0.85146332 0.18796568 0.15930079]
 [0.90327035 0.92866363 0.82464954 0.39711884 0.35029097 0.36991114
  0.74806931 0.33115818 0.97746235 0.89139528]
 [0.16276808 0.7192251  0.14240315 0.38577815 0.22441165 0.55572306
  0.27232974 

In [ ]:
# создать вектор из 30 случайных чисел и вывести среднее значение
a = np.random.random(30)
print(a)
print(a.mean())

[0.83526144 0.11054074 0.36025129 0.41794202 0.50949428 0.7061641
 0.78260987 0.92665111 0.42703553 0.88925692 0.76553149 0.11502529
 0.49062675 0.66188921 0.77291724 0.30168993 0.19535618 0.63095545
 0.35685875 0.11359042 0.48507766 0.99989721 0.19766111 0.9741225
 0.28859    0.74715535 0.66770594 0.05838086 0.56330816 0.84335183]
0.5398299534034218


In [ ]:
# создать матрицу 10х10 из нулей и единицами по границам матрицы
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# создать матрицу 5х5 из единиц и превратить ее в 7х7, окружив нули единицами по границе матрицы
a = np.ones((5, 5))
a = np.ones((7, 7))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# создать матрицу 7х7 из единиц в середине и нулей по периметру, используя индексацию
a = np.zeros((7, 7))
a[1:-1,1:-1] = 1
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# что будет результатом каждой строки?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

# проверьте свои предположения


False

In [ ]:
# создать (код в одну строку) матрицу 5х5 из нулей и чисел 1 2 3 4 под главной диагональю
a = np.diag(np.arange(1, 5), k =- 1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# создать (через работу со срезами) матрицу 8х8, заполнив ее нулями и единицами по образу шахматной доски
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# создать (код в одну строку с использованием библиотечной функции) матрицу 8х8,
# заполнив ее нулями и единицами по образу шахматной доски
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# в тензоре 6х7х8 найти индексы сотого элемента (счет элементов идет по слоям)
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [ ]:
# создать матрицу 5х5 из случайных чисел и нормализовать ее
a = np.random.random((5, 5))
a = (a - np.mean(a)) / (np.std(a))
print(a)

[[ 0.95560257  0.22282863  0.75121527 -0.52011482  0.37561181]
 [-0.58749741  1.62258718  1.58761914  1.43629341 -0.8632197 ]
 [-0.84372749  0.99596534 -0.43997664 -1.26560637  0.86757829]
 [-0.6308487  -0.87072772 -0.88170795 -1.25314929  0.35575198]
 [ 0.73249238 -1.39391836 -0.67822423 -1.2302393   1.55541199]]


In [ ]:
# выполнить матричное умножение матриц 5х3 и 3х2 из единиц
a = np.dot(np.ones((5,3)), np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# написать умножение тензора 5х5х3 на матрицу 5х3
a = np.arange(5 * 5 * 3).reshape(5, 5, 3)
b = 2 * np.ones((5, 5))
a * b[:, :, None]

array([[[  0.,   2.,   4.],
        [  6.,   8.,  10.],
        [ 12.,  14.,  16.],
        [ 18.,  20.,  22.],
        [ 24.,  26.,  28.]],

       [[ 30.,  32.,  34.],
        [ 36.,  38.,  40.],
        [ 42.,  44.,  46.],
        [ 48.,  50.,  52.],
        [ 54.,  56.,  58.]],

       [[ 60.,  62.,  64.],
        [ 66.,  68.,  70.],
        [ 72.,  74.,  76.],
        [ 78.,  80.,  82.],
        [ 84.,  86.,  88.]],

       [[ 90.,  92.,  94.],
        [ 96.,  98., 100.],
        [102., 104., 106.],
        [108., 110., 112.],
        [114., 116., 118.]],

       [[120., 122., 124.],
        [126., 128., 130.],
        [132., 134., 136.],
        [138., 140., 142.],
        [144., 146., 148.]]])

In [ ]:
# найти самое частое значение в матрице
Z = np.random.randint(10, size = (10, 10))
Z_bincount_flat = np.bincount(Z.flatten())
top_elem = Z_bincount_flat.argmax()
top_elem

8

In [ ]:
# для матрицы 16х16 вывести матрицу из сумм блоков 4х4
a = np.ones((16,16))
k = 4
b = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
b

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [ ]:
# преобразовать вектор целых чисел в матрицу их двоичного представления
arr_numbers = np.array([0, 1, 2, 3, 15, 16, 64, 255, 256, 1024])
import math

max_number = arr_numbers.max()
N = math.ceil(np.log2(max_number)) + 1

binary_numbers = ((arr_numbers.reshape(-1, 1) & (2 ** np.arange(N))) != 0).astype(int)
binary_numbers = binary_numbers[:, ::-1]
binary_numbers

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# для матрицы вывести все уникальные строки
Z = np.random.randint(0, 20, (10, 3))
uniq_rows_Z2 = np.unique(Z, axis=0)
len_arr = len(uniq_rows_Z2)
len_arr

10